PUT   http://localhost:3000/update 
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoi5byg5LiJIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpYXQiOjE2NTAyODU1NjAsImV4cCI6MTY1MDM3MTk2MH0.TmEau1iArcV94_Q6VD4nzPtt8vExWIoS3Nv1i_sMMz0

{   
    "uu_id":"E3D8AB7D-82BC-3804-D3CB-EDB4EBA8EF4D",
    "userName": "张三",
    "oldPassword": "654321",
    "newPassword":"123456"
}